### ISSUE TITLE
manual sync failing in API

### ISSUE THREAD

**Issue by cgardens** [datalineio/dataline#200]
## Expected Behavior
* setting a null schedule should make a connection manual sync only.

## Current Behavior
* sending null returns a json error saying schedule is required

## Other
* glanced at the config and it looks like it right. new

**Comment by sherifnada** [comment]
@cgardens how can this issue be reproduced? Can we test if it still exists now that #245 has landed?

**Comment by cgardens** [comment]
i think this works fine since your pr.
