### ISSUE TITLE
Track events not well logged on docs.dataline.io

### ISSUE THREAD

**Issue by johnlafleur** [datalineio/dataline#252]
## Expected Behavior
*Tell us what should happen.*
When visiting a documentation page, in Segment's debugger (https://app.segment.com/dataline/sources/dataline-website/debugger), I should see 2 events:
- TRACK: "Viewed [Page Name] Page" 
- PAGE: /deployment/deploying-dataline/with-docker (for instance)

## Current Behavior
*Tell us what happens instead of the expected behavior.*
We currently only see the PAGE event. The issue with this is that we won't see this issue in the analytics tools (Amplitude / etc). 

## Steps to Reproduce
1. Go to any docs page
2. Check debugger on Segment, and you'll only see the PAGE event, and not the TRACK one.

## Severity of the bug for you
Very low / Low / Medium / High / Critical
Medium

## Additional context
*Environment, version, integration...*
We had a similar issue in the past. The solution is in passing the name of the page in the Segment event, so that "Track Named Pages" works on Segment. As an example, this would be a page call with a name of Pricing passed in:
analytics.page('Pricing');

**Comment by michel-tricot** [comment]
Before I spend time on it, what does track gives us that page doesn't?

**Comment by johnlafleur** [comment]
Without TRACK, you can't see these events on any analytics tools (so Amplitude, GA, ...). 
The PAGE event is mostly useless without the TRACK one.

**Comment by michel-tricot** [comment]
Done
