### ISSUE TITLE
Date format should be explicit in placeholder

### ISSUE THREAD

**Issue by johnlafleur** [datalineio/dataline#264]
## Expected Behavior
When adding Postgres source, a field is asking for start_date, and apparently, we need the format YYYY-MM-DD, otherwise it won't work. We need to make it explicit in the placeholder, such as in the screenshot. 

Another solution is to put the format as a description, what do you think @cgardens ?

<img width="288" alt="Screen Shot 2020-09-15 at 10 12 59 AM" src="https://user-images.githubusercontent.com/68561602/93147088-4111b780-f73c-11ea-9ceb-237da3279774.png">

## Current Behavior
There is no info about which format is expected for the date.

**Comment by cgardens** [comment]
@Jamakase for this let's take a similar approach as with the descriptions. We will populate the `examples` field on the field there is an example we want to show. According to the jsonschema spec it looks like examples is expected to be an array of strings. you can assume that the first element in the array, if it exists is the one we want to display. Does that work?
