### ISSUE TITLE
Editing syncing frequency doesn't work

### ISSUE THREAD

**Issue by johnlafleur** [datalineio/dataline#277]
## Expected Behavior
In a source detail page, in Settings tab, when editing the syncing frequency and clicking on Save changes, I should see a feedback and also the [Save changes] button should become disabled as the user saved the changes they already made. 
See specs here for the feedback: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=7055%3A18

But more importantly, the new frequency should be saved. Right now, the change is not saved. 

## Current Behavior
When clicking on "Save changes" (after editing the frequency), nothing happens and nothing is saved.

**Comment by johnlafleur** [comment]
Please note that the feedback experience described above should apply for any editing happening (for instance, if you only edit the name and click on "Save changes" too).

**Comment by cgardens** [comment]
> But more importantly, the new frequency should be saved. Right now, the change is not saved.


@johnlafleur can you reproduce this and see if there are any options in your browser console. i just tried to do this myself locally and everything worked well. if might be helpful if we could see the error you're getting.
