### ISSUE TITLE
Descriptions should display links and not html

### ISSUE THREAD

**Issue by johnlafleur** [datalineio/dataline#323]
## Expected Behavior
Descriptions don't seem to display <a href> properly. They should be displaying the link, not the html. 
See screenshot
<img width="873" alt="Screen Shot 2020-09-17 at 11 45 51 AM" src="https://user-images.githubusercontent.com/68561602/93407935-19a72000-f8df-11ea-9031-2ed6580d0061.png">

@cgardens

**Comment by cgardens** [comment]
duplicate: https://github.com/datalineio/dataline/issues/319
